version: "3.8"

services:
  postgresdb:
    image: postgres:17.5
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT

  app:
    depends_on:
      - postgresdb
    image: batch-processing
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: no